spring:
  profiles:
    active: dev


#log
logging:
  level:
    root: info
    com:
      laywerspringboot:
        edition:
          dao: debug
          controller: debug

  file:
    path: \G:\log
    name: daylog
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.xx.xxx.entity
  type-aliases-package: com.laywerspringboot.edition.entity
  configuration:
    map-underscore-to-camel-case: true
  # mapper-locations: classpath:dao/*.xml


