server:
  port: 80
  address: 0.0.0.0
spring:
  datasource:
    druid:
      #url: jdbc:mysql://49.235.115.228:3306/myrhythm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      #url: jdbc:mysql://db10:3306/myrhythm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

      url: jdbc:mysql://127.0.0.1:3306/myrhythm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      #password: QFedu123@
      #password: 4235499Huang!
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

#log
logging:
  level:
    root: info
    com:
      laywerspringboot:
        edition:
          dao: debug
          controller: debug
  file:
    path: \G:\log
    name: day.log
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.xx.xxx.entity
  type-aliases-package: com.laywerspringboot.edition.entity
  configuration:
    map-underscore-to-camel-case: true
  # mapper-locations: classpath:dao/*.xml


